<div class="loc_cont">

    <!-- Image Map Generated by http://www.image-map.net/ -->
<div class='loc_grid_cont'>
<!-- To put the artworks in a specific location next to the map using a grid -->
<div class="grid-item-loc" id="loc_school_Map">
    <img src="img/school_map2.png" usemap="#image-map" class="map">
    <!-- Defining the 'clicking area' on the map (each building) -->
   <!-- <map name="image-map">
        <area alt="M-Block" title="M-Block" onclick="mblock_f()" target="_blank" coords="234,317,315,275,348,332,276,373" shape="poly" id="mblock-poly"onmouseover="this.style.backgroundColor='#00FF00';">

        <area alt="G-Block" title="G-Block" onclick="gblock_f()" target="_blank" coords="358,211,387,199,411,255,381,270" shape="poly" id="gblock-poly">

        <area alt="C-Block" title="C-Block" onclick="cblock_f()" target="_blank" coords="217,239,141,289,159,386,197,362,183,326,245,282" shape="poly" id="cblock-poly">
    </map> -->
    <!-- Image Map Generated by http://www.image-map.net/ -->
<img src="school_map2.png" usemap="#image-map">

<map name="image-map">
    <area class="allpolys" target="_blank" alt="cblock" title="cblock" href="" coords="221,234,138,291,160,388,201,364,184,326,252,285" shape="poly" onmouseover="this.style.backgroundColor='#00FF00'" id="cblock-poly">
   
    <area class="allpolys" id="wblock-poly" target="_blank" alt="wblock" title="wblock" href="" coords="197,334,228,403,266,383,221,319" shape="poly">
    <area class="allpolys" id="mblock-poly" target="_blank" alt="mblock" title="mblock" href="" coords="244,317,277,375,344,328,313,274" shape="poly">
    <area class="allpolys" id="bblock-poly" target="_blank" alt="bblock" title="bblock" href="" coords="304,201,311,254,351,253,342,199" shape="poly">
    <area class="allpolys" id="lblock-poly" target="_blank" alt="lblock" title="lblock" href="" coords="120,371,135,453,220,402,205,366,153,394,148,350,120,363" shape="poly"> 
    <area class="allpolys" id="gblock-poly" target="_blank" alt="gblock" title="gblock" href="" coords="360,212,380,267,405,261,388,205" shape="poly">

    <script>
    $('.allpolys').on('click', function(e){
        e.preventDefault();
        var buildingId = jQuery(this).attr("id") + "b";
        //alert(buildingId);
        $(".alltiles").hide();
        $('#featuredtile').show();
        $("#" + buildingId).show();
    
    })</script>
</map>

<script>
    
    /*
    $("#cblock-poly").on("click", function(e){
    e.preventDefault();
    var contentPanelId = jQuery(this).attr("id");
    alert(contentPanelId);
    $(".allpolys").hide();
    //$("#test12").toggle();
});
    </script>
</div>


<div class="grid-item-loc loc_desc" id="desc_cont" style=" overflow: scroll;">
<!-- Information on the artworks in the building will be displayed here -->
    <h2 id="loc_block_name">Locations</h2>
    <!-- In a fully developed version, the 'featured' artwork will be different for each building -->
    
    <div id="loc_home" class="alltiles">
        <p>Many artworks are currently on display around the school. Click on a building (on the map) to find the artworks currently being exhibited in it. </p> <br>
        <div style="text-align: center;"><img src="img/512823.jpg" alt="Evolution" width = "300px" height = "auto" ><br>
        <!-- Image caption -->
        <caption><strong>Evolution </strong><i>Oil Painting by Irene Amos. </i>Find it on M202</caption>
        </div>
    </div>
    <div class="alltiles" id="cblock-polyb" hidden>
        <h2>C Block Artworks</h2>
        <?php include 'includes/cBlock.inc.php';?>
    </div>
    <!-- Links to external php pages that contain the connection to the database to gather data on the artworks in a building using SQL queries. The same code is in each file, with small ammendments to the SQL. -->
    <div class="alltiles" id="mblock-polyb" hidden>
    <h2>M Block Artworks</h2>
    <?php include 'includes/mBlock.inc.php' ?>
    </div>

    <!-- Developer note: Is it possible use only one page but use variables? -->
    <div class="alltiles" id="gblock-polyb" hidden>
    <h2>G Block Artworks</h2>
    <?php include 'includes/gBlock.inc.php'; ?>
    </div>
    
</div>
<script src="scripts/loc_script.js"></script>
<!-- Add jQuery library -->
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.min.js"></script>

<!-- Add maphilight plugin -->
<script type="text/javascript" src="http://davidlynch.org/projects/maphilight/jquery.maphilight.js"></script>

<!-- Activate maphilight plugin -->
<script type="text/javascript">$(function() {
        $('.map').maphilight();
    });
</script> 
</div>

    </div>
    </div>

</div>

